export const INCREASE_CART_BADGE_COUNT = 'INCREASE_CART_BADGE_COUNT';
export const DECREASE_CART_BADGE_COUNT = 'DECREASE_CART_BADGE_COUNT';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const SELECT_PRODUCT_VARIANT = 'SELECT_PRODUCT_VARIANT';

export const GET_PRODUCT_VARIANTS_REQUEST = 'GET_PRODUCT_VARIANTS_REQUEST';
export const GET_PRODUCT_VARIANTS_SUCCESS = 'GET_PRODUCT_VARIANTS_SUCCESS';
export const GET_PRODUCT_VARIANTS_FAILURE = 'GET_PRODUCT_VARIANTS_FAILURE';

export const SET_PRODUCT_IN_CART_QUANTITY = 'SET_PRODUCT_IN_CART_QUANTITY';

export const RESET_PRODUCT_IN_CART = 'RESET_PRODUCT_IN_CART';
