
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const SELECT_PRODUCT_VARIANT = 'SELECT_PRODUCT_VARIANT';

export const GET_PRODUCT_VARIANTS_REQUEST = 'GET_PRODUCT_VARIANTS_REQUEST';
export const GET_PRODUCT_VARIANTS_SUCCESS = 'GET_PRODUCT_VARIANTS_SUCCESS';
export const GET_PRODUCT_VARIANTS_FAILURE = 'GET_PRODUCT_VARIANTS_FAILURE';

export const SET_PRODUCT_IN_CART_QUANTITY = 'SET_PRODUCT_IN_CART_QUANTITY';

export const RESET_PRODUCT_IN_CART = 'RESET_PRODUCT_IN_CART';

export const EDIT_FROM_CART = 'EDIT_FROM_CART';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
